### ISSUE TITLE
Change file format 

### ISSUE THREAD

**Issue by anbuharry** [AlexMetsai/Video-Deep-Features#2]
In this code extracting feature from video and frames are stored as pt file. but I want to store it in h5 format how can I do that?

**Comment by AlexMetsai** [comment]
I think that `torch.save()` supports the hdf5 format, therefore changing line 164:

`filename = video_folder + file[:-4] + "_features.pt"`

to:
`filename = video_folder + file[:-4] + "_features.h5"`

should do the trick. I'll try to test it at the near future (and maybe implement argument parsing for better usability) but I think it will be easy to apply this yourself. ;)

**Comment by anbuharry** [comment]
> I think that `torch.save()` supports the hdf5 format, therefore changing line 164:
> 
> `filename = video_folder + file[:-4] + "_features.pt"`
> 
> to:
> `filename = video_folder + file[:-4] + "_features.h5"`
> 
> should do the trick. I'll try to test it at the near future (and maybe implement argument parsing for better usability) but I think it will be easy to apply this yourself. ;)

@AlexMetsai Thank you
