### ISSUE TITLE
Extracting feature from multi view video 

### ISSUE THREAD

**Issue by anbuharry** [AlexMetsai/Video-Deep-Features#3]
Hai @AlexMetsai 

Thank you so much for uploading this code its really working good and helpful for me.

I need to extract feature from video with time-based how can I do that could you help me to do this problem

problem statement :
if you give 3 videos as input I want to extraction frames based on time, how this way extracted feature from video

Thank you

**Comment by AlexMetsai** [comment]
Hi Hariprasath,

Thank you for your kind words. Extracting a frame at an EXACT moment is a non-trivial task, however, for deep learning tasks where frames that are close are fine, you can do a simple interpolation, maybe you can select the desired frame using something like (pseudo code):

`desired_frame = (total_frames * desired_seconds) / video_length_seconds`

I think this won't be hard to implement.

Best,
Alex

**Comment by anbuharry** [comment]
Hai @AlexMetsai 

Once again 

How to extract feature from multiple video and stored as individual .pth file for Every video

**Comment by AlexMetsai** [comment]
Hi there @anbuharry,

What you 're asking for is the default behavior, a separate pickle file is stored for each video. Correct me if I'm mistaken. ;)

[line 172](https://github.com/AlexMetsai/Video-Deep-Features/blob/master/feature_vector_extraction.py#L172)
